### ISSUE TITLE
/api/accesspoint

### ISSUE THREAD

**Issue by rogerlangedal** [birno/BossIDWS.Vendor#4]
In the skeleton project we've used the enum AccessPointType to validate input - with a range of values from 1-5:
public enum AccessPointType
        {
            /// <summary>
            /// Access point ID in the vendor system
            /// </summary>
            ID = 1,
            /// <summary>
            /// The tag of the access point
            /// </summary>
            TAG = 2,
            /// <summary>
            /// Name or address of access point
            /// </summary>
            NAME = 3,
            /// <summary>
            /// All access points. The AccessPoint parameter is empty
            /// </summary>
            ALL = 4,
            /// <summary>
            /// 
            /// </summary>
            NA = 5
        }

So a valid body might be:
{"InstallationID": 123, "Type": "4"}  //representing ALL

while you seem to only allow the textual value "ALL"? is that correct

**Comment by tgarbowski** [comment]
Another thing here is, the enum's value set is bigger than in the specification - there is no 5 - NA allowed value there. The question is what should we do when someone calls us with this value? Is it the same as ALL?

**Comment by rogerlangedal** [comment]
You are correct - I've corrected the enum and removed the NA. I know the spec specifies a string to be passed - but I'd rather use an enum if it's all the same with you? If nolet me know and I'll pass as string as the spec dictates

**Comment by tgarbowski** [comment]
OK, we can do that and change the parameter to accept the integer values of the enum, instead of strings. This change will also affect the 7.7.4 AccessPointDetails and the 7.9.2 AccessPointOutOfOrder methods - **please confirm.** 
Also, please, change the specs so that the api is in line with the documentation.

**Comment by rogerlangedal** [comment]
confirmed. I think we'll have to have a separate spec for the REST interface anyway - there is quite few things that will differ between them.

**Comment by tgarbowski** [comment]
OK, but please make the specs and the changes to be introduced available to us ASAP because we're pressed by the customer to finish the integration. Also, please submit those changes as separate issues here so that we can back-reference them in our code - thanks :-).

**Comment by rogerlangedal** [comment]
I was primarily talking about that the bossid spec contains quite a few references to the formatting of xml and such that is not needed in the REST spec. Thus the REST spec would pretty much be a subset of the bossid spec. But as I've said before - the REST interface is a work in progress - although very close. Changes like this issue with enums versus string values are in my opinion small changes that makes validation easier on both sides. Those are the differences I think we should take the time to implement now - before we lock everything down completely :-) I appreciate the fact that you have client requirements to finish asap and I'll try to minimize the impact this will have on your timeline.

**Comment by tgarbowski** [comment]
changes to AccessPointType parameter ready for testing
