### ISSUE TITLE
CustomerMove

### ISSUE THREAD

**Issue by rogerlangedal** [birno/BossIDWS.Vendor#5]
When I try to move a customer I get this error:

customerKey: WartoÅ›Ä‡ nie speÅ‚nia zaÅ‚oÅ¼onych niestandardowych warunkÃ³w

The json I'm sending in is this:

{"Name":"new name","PropertyUnit":"some unit","StreetAddress":"new address","Description":"new description","Primary":"1","Secondary1":"2","Secondary2":"3","Customerkey":"1","InstallationID":"123"}

**Comment by tgarbowski** [comment]
new version deployed, please re-test

**Comment by rogerlangedal** [comment]
Tested ok
