### ISSUE TITLE
CustomerAccessPoints

### ISSUE THREAD

**Issue by rogerlangedal** [birno/BossIDWS.Vendor#6]
This method seems to return an errorcode of 0 - but no accesspoints in the returnvalue. The client should have accesspoints:

Json request object:
{"Customerkey":"2","InstallationID":"123"}

**Comment by wdelezuch** [comment]
I checked database and I don't see assigned access points to any customer. Did you added any with customer? 
Valid access points ids that you can use: 1718, 1719, 1720. You can check them by posting https://testapp.ecobins.pl/ext/api/accesspoint

**Comment by tgarbowski** [comment]
Can you try to assign one of the access points through the api to this customer and then do the test again?

**Comment by rogerlangedal** [comment]
Hi, I've created an new customer - id = 4 now and it seems to return the correct values from customer accesspoint :-)

The errro is related to the fact that when I created clients yesterday I put the names of the accessspoint (1,2,3) in insted of the id's (1718, 1719, 1720). You should probably return an error if we should happen to send in a new client referencing accesspoints that do not exist in your system

**Comment by tgarbowski** [comment]
>  You should probably return an error if we should happen to send in a new client referencing  access points that do not exist in your system
We thought about adding such a verification but the question is how the system should behave when at least one of the access point ids is correct - for example (1718, 2, 3)? Should we stop the transaction and raise an error or register the customer and assign to him/her all the correct access points (1718 in this example), ignoring the wrong ones?

**Comment by rogerlangedal** [comment]
The data is validated in BossID prior to sending to you - so no invalid accesspoint should be coming over. The only scenario I can think of would be if the imported accesspoints in Bossid at some point is out of sync with the accesspoins on your side...i.e if an accesspoint on your side was removed from the system - without bosside knnowing it? I think that the safest course of action is that if any accesspoint is not found in your system - fail the entire transaction end return an error...

**Comment by tgarbowski** [comment]
> ...I think that the safest course of action is that if any accesspoint is not found in your system - fail the entire transaction end return an error...

Done. Please re-test.
