### ISSUE TITLE
Customerevents

### ISSUE THREAD

**Issue by rogerlangedal** [birno/BossIDWS.Vendor#7]
CustomerEvents return errorcode - but no events for an existing client

There might be no events - but could you create som sample events just so it's easier to test the returned values?

**Comment by wdelezuch** [comment]
Yes, we can create sample events, but this is related to task #6 - we need to know which access points the client can use.

**Comment by rogerlangedal** [comment]
Let's use client #4 events can be linked to any three accesspoint

**Comment by wdelezuch** [comment]
I created sample events for client 4.

**Comment by rogerlangedal** [comment]
I tried to grab events now - getting 15 results when asking /api/client/events with ALL
{"Customerkey":"ALL","FromDate":"2017-01-18T12:11:55.0786644+01:00","ToDate":"2017-04-28T12:11:55.0796643+02:00","InstallationID":"123"}

But if I ask /api/client/events spesifically for client 4's events I still get 0?
{"Customerkey":"4","FromDate":"2017-01-18T12:11:55.2296723+01:00","ToDate":"2017-04-28T12:11:55.2296723+02:00","InstallationID":"NA"}

**Comment by rogerlangedal** [comment]
Sorry - my bad :-P Saw it as soon as I posted - missing installationID :-D
