### ISSUE TITLE
JSON compression support

### ISSUE THREAD

**Issue by tgarbowski** [birno/BossIDWS.Vendor#8]
Add support to compress the returned json values.

**Comment by tgarbowski** [comment]
New version deployed. Ready for testing: the json compression is activated for responses larger than 2kB.

**Comment by rogerlangedal** [comment]
Not entirely sure how to verify compressionresults - suggestions?

**Comment by tgarbowski** [comment]
Sorry, we forgot to switch the compression on the server for this environment ;-). It is on now so you can retest. Basically you should add accept-encoding: gzip header to the request to get the compressed response. To verify that the raw data actually returned from our server is gzipped use this curl command for example:

`curl --request POST   --url https://testapp.ecobins.pl/ext/api/client/events   --header 'accept-encoding: gzip'   --header 'api-key: <here goes the key....>'   --header 'cache-control: no-cache'   --header 'content-type: application/json'   --data '{"InstallationID": 123, "Customerkey": 4}'`

**Comment by rogerlangedal** [comment]
Tested and content seems to return "Content-Encoding →gzip" properly :-)
