### ISSUE TITLE
customeraccesspoints

### ISSUE THREAD

**Issue by rogerlangedal** [birno/BossIDWS.Vendor#9]
When calling /api/accesspoint with the JSON - indicating I want to search by NAME - I get back 2 results 
{"Type":3,"AccessPoint":"2","InstallationID":"123"}

Should give one and only one result?

Also - I was not able to test the search by TAG as the tags are empty on all three accesspoints :-)

**Comment by tgarbowski** [comment]
@wdelezuch - please check the response from this request
@rogerlangedal - the TAGs are not implemented in our containers/access points so they are not available through the  api - are they compulsory?

**Comment by wdelezuch** [comment]
You received 2 results because we search for access points using the like operator. We can change the operator to "=", if you will always give us the full name, but what if the name is not unique?

**Comment by rogerlangedal** [comment]
Ok - If you do not support tags we'll leave it as is. 
For the name operator we should have "name =" - should either fint 1 name or return nothing found.
The name given to an accesspoint should be unique within the same installation(id)

**Comment by tgarbowski** [comment]
> For the name operator we should have "name =" - should either fint 1 name or return nothing found.

Done. Please re-test.

**Comment by rogerlangedal** [comment]
All good!
